import { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { selectFilteredEmployees, deleteEmployee } from "./employeeSlice";
import {
  Edit2,
  Trash2,
  CheckCircle,
  XCircle,
  ChevronLeft,
  ChevronRight,
  Printer,
} from "lucide-react";
import { format } from "date-fns";
import { toast } from "react-hot-toast";
import Button from "../../components/ui/Button";
import jsPDF from "jspdf";

const EmployeeTable = ({ onEdit }) => {
  const employees = useSelector(selectFilteredEmployees);
  const dispatch = useDispatch();

  // Pagination State
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  // Calculate pagination
  const totalPages = Math.ceil(employees.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const currentEmployees = employees.slice(
    startIndex,
    startIndex + itemsPerPage
  );

  const handleDelete = (id) => {
    if (window.confirm("Are you sure you want to delete this employee?")) {
      dispatch(deleteEmployee(id));
      toast.success("Employee deleted successfully");
    }
  };

  const handleDownloadProfile = (emp) => {
    const doc = new jsPDF();

    // Background
    doc.setFillColor(249, 250, 251); // Gray 50
    doc.rect(0, 0, 210, 297, "F");

    // Header Decoration
    doc.setFillColor(79, 70, 229); // Primary 600
    doc.rect(0, 0, 210, 40, "F");

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Employee Profile", 105, 25, { align: "center" });

    // Card Container
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(20, 55, 170, 180, 5, 5, "F");
    doc.setDrawColor(229, 231, 235); // Border gray
    doc.roundedRect(20, 55, 170, 180, 5, 5, "S");

    // Employee Name
    doc.setTextColor(17, 24, 39); // Gray 900
    doc.setFontSize(24);
    doc.text(emp.name, 105, 80, { align: "center" });

    // Role/ID
    doc.setTextColor(107, 114, 128); // Gray 500
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Employee ID: #${emp.id}`, 105, 90, { align: "center" });

    // Divider
    doc.setDrawColor(243, 244, 246);
    doc.line(40, 100, 170, 100);

    // Details Grid
    const startY = 120;
    const lineHeight = 15;
    const col1X = 50;
    const col2X = 110;

    const details = [
      { label: "Status", value: emp.active ? "Active" : "Inactive" },
      { label: "Gender", value: emp.gender },
      {
        label: "Date of Birth",
        value: format(new Date(emp.dob), "MMMM d, yyyy"),
      },
      { label: "State", value: emp.state },
    ];

    details.forEach((item, index) => {
      const yPos = startY + index * lineHeight;

      // Label
      doc.setFont("helvetica", "bold");
      doc.setTextColor(75, 85, 99);
      doc.setFontSize(11);
      doc.text(item.label, col1X, yPos);

      // Value
      doc.setFont("helvetica", "normal");
      doc.setTextColor(17, 24, 39);
      doc.text(item.value, col2X, yPos);
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text("Generated by Employee Dashboard", 105, 220, { align: "center" });

    doc.save(`${emp.name.replace(/\s+/g, "_")}_profile.pdf`);
    toast.success("Profile downloaded");
  };

  const goToPage = (page) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  // Reset page if filtered results change significantly
  if (currentPage > totalPages && totalPages > 0) {
    setCurrentPage(totalPages);
  }

  if (employees.length === 0) {
    return (
      <div className="text-center py-12 bg-white rounded-xl border border-gray-100 border-dashed">
        <p className="text-gray-500">
          No employees found matching your criteria.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden flex flex-col h-full">
      <div className="overflow-x-auto flex-1 custom-scrollbar">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100 text-xs uppercase text-gray-500 font-semibold tracking-wider sticky top-0 z-10 shadow-sm">
              <th className="px-6 py-4 bg-gray-50">Employee</th>
              <th className="px-6 py-4 bg-gray-50">ID</th>
              <th className="px-6 py-4 bg-gray-50">Status</th>
              <th className="px-6 py-4 bg-gray-50">Details</th>
              <th className="px-6 py-4 text-right bg-gray-50">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {currentEmployees.map((emp, index) => (
              <tr
                key={emp.id}
                className="hover:bg-gray-50/80 transition-all duration-300 group hover:shadow-sm hover:scale-[1.002] border-b border-gray-50 last:border-0 animate-in fade-in slide-in-from-bottom-2 fill-mode-forwards"
                style={{ animationDelay: `${index * 50}ms` }}
              >
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <img
                      src={
                        emp.image ||
                        `https://ui-avatars.com/api/?name=${emp.name}&background=random`
                      }
                      alt={emp.name}
                      className="w-10 h-10 rounded-full object-cover border-2 border-white shadow-sm"
                    />
                    <div>
                      <p className="font-medium text-gray-900">{emp.name}</p>
                      <p className="text-xs text-gray-500">{emp.gender}</p>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  #{emp.id.slice(0, 6)}
                </td>
                <td className="px-6 py-4">
                  <span
                    className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium ${
                      emp.active
                        ? "bg-green-50 text-green-700 border border-green-100"
                        : "bg-gray-100 text-gray-600 border border-gray-200"
                    }`}
                  >
                    {emp.active ? (
                      <CheckCircle size={12} />
                    ) : (
                      <XCircle size={12} />
                    )}
                    {emp.active ? "Active" : "Inactive"}
                  </span>
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  <div className="flex flex-col">
                    <span>{emp.state}</span>
                    <span className="text-xs text-gray-400">
                      {format(new Date(emp.dob), "MMM d, yyyy")}
                    </span>
                  </div>
                </td>
                <td className="px-6 py-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <button
                      onClick={() => handleDownloadProfile(emp)}
                      className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                      title="Print Profile"
                    >
                      <Printer size={16} />
                    </button>
                    <button
                      onClick={() => onEdit(emp)}
                      className="p-2 text-gray-400 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-colors"
                      title="Edit"
                    >
                      <Edit2 size={16} />
                    </button>
                    <button
                      onClick={() => handleDelete(emp.id)}
                      className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination Controls */}
      <div className="border-t border-gray-100 px-6 py-4 bg-gray-50/50 flex items-center justify-between flex-shrink-0">
        <span className="text-sm text-gray-500">
          Showing <span className="font-medium">{startIndex + 1}</span> to{" "}
          <span className="font-medium">
            {Math.min(startIndex + itemsPerPage, employees.length)}
          </span>{" "}
          of <span className="font-medium">{employees.length}</span> results
        </span>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={currentPage === 1}
            onClick={() => goToPage(currentPage - 1)}
            className="bg-white h-8 w-8 p-0 flex items-center justify-center"
          >
            <ChevronLeft size={16} />
          </Button>
          <span className="text-sm font-medium text-gray-700 w-8 text-center">
            {currentPage}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={currentPage === totalPages}
            onClick={() => goToPage(currentPage + 1)}
            className="bg-white h-8 w-8 p-0 flex items-center justify-center"
          >
            <ChevronRight size={16} />
          </Button>
        </div>
      </div>
    </div>
  );
};

export default EmployeeTable;
